services:
  database_dev:
    image: postgres:17-alpine
    container_name: database_dev
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - envs/dev/.env
    volumes:
      - dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 3s
      timeout: 3s
      retries: 5
volumes:
  dev_data: {}
