services:
  database_test:
    image: postgres:17-alpine
    container_name: database_test
    restart: always
    ports:
      - "5434:5432"
    env_file:
      - ./envs.example/test/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 3s
      timeout: 3s
      retries: 5
  api_test:
    container_name: api_test
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.tests
      args:
        PYTHON_VERSION: "${PYTHON_VERSION:-3.13}"
    healthcheck:
      test: python manage.py healthcheck
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      database_test:
        condition: service_healthy
        restart: true
      redis_test:
        condition: service_healthy
        restart: true
    env_file:
      - ./envs.example/test/.env
    environment:
      # overloaded because tests are executed inside the application container (FastApi)
      CELERY_BROKER: redis://:requirepass@redis_test:6379/0
      CELERY_BACKEND: redis://:requirepass@redis_test:6379/0
      POSTGRES_HOST: database_test
      POSTGRES_PORT: 5432
    volumes:
      - ./src:/home/appuser/app/www
      - ./conftest.py:/home/appuser/app/www/conftest.py
      - ./tox.ini:/home/appuser/app/www/tox.ini
      - ./.coveragerc:/home/appuser/app/www/.coveragerc
    command: ["bash", "./scripts/entrypoint.sh"]

  redis_test:
    image: meschac38000/redis-fastapi
    container_name: redis_test
    restart: always
    env_file:
      - ./envs.example/test/.env
    environment:
      # overloaded because tests are executed inside the application container (FastApi)
      CELERY_BROKER: redis://:requirepass@redis_test:6379/0
      CELERY_BACKEND: redis://:requirepass@redis_test:6379/0
    ports:
      - "63791:6379"
    privileged: true
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "--no-auth-warning", "--pass $$REDIS_PASSWORD", "--raw ping | grep PONG" ]
      interval: 3s
      timeout: 3s
      retries: 5
    command: sh -c "./entrypoint.sh"

  celery_test:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.tests
    container_name: celery_test
    restart: on-failure
    env_file:
      - ./envs.example/test/.env
    depends_on:
      api_test:
        condition: service_healthy
        restart: true
    volumes:
      - ./src:/home/appuser/app/www
    environment:
      # overloaded because tests are executed inside the application container (FastApi)
      CELERY_BROKER: redis://:requirepass@redis_test:6379/0
      CELERY_BACKEND: redis://:requirepass@redis_test:6379/0
    command: bash -c "celery -A main.celery worker -n default@%h -Q default --loglevel=INFO"
