services:
  database-dev:
    image: postgres:14.8-alpine
    container_name: database-dev
    restart: always
    ports:
      - 5433:5432
    env_file:
      - envs/dev/.env
    volumes:
      - dev_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 3s
      timeout: 3s
      retries: 5
  api:
    container_name: api-dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.13}
    depends_on:
      database-dev:
        condition: service_healthy
        restart: true
    volumes:
      - ./src:/home/appuser/app/www
    env_file:
      - envs/dev/.env
    command: ["bash", "./scripts/entrypoint.dev.sh"]
volumes:
  dev_data: {}
