services:
  database:
    image: postgres:14.8-alpine
    container_name: database
    restart: always
    ports:
      - 5432:5432
    env_file:
      - envs/prod/.env
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 3s
      timeout: 3s
      retries: 5
  api:
    container_name: api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.13}
    volumes:
      - ./src:/home/appuser/app/www
    ports:
      - "8001:8001"
    env_file:
      - envs/prod/.env

volumes:
  data: {}
