"""Add chat models: ChatRoom & ChatMessage

Revision ID: 1dc2007bee4a
Revises: c5da92aa72eb
Create Date: 2025-07-19 16:35:06.846131

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "1dc2007bee4a"
down_revision: Union[str, None] = "c5da92aa72eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
