"""Add User.status field

Revision ID: 20055947a674
Revises: b991d39149d2
Create Date: 2025-05-31 22:58:05.690154

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "20055947a674"
down_revision: Union[str, None] = "b991d39149d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

status_enum = postgresql.ENUM("active", "inactive", name="status")


def upgrade() -> None:
    # Create the new enum type
    status_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("status", status_enum, nullable=True, server_default="inactive"),
    )
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_status"), table_name="users")
    op.drop_column("users", "status")

    status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
