"""Rename user table to users to void conflict

Revision ID: 20286263e186
Revises: aadd9ba89966
Create Date: 2025-04-08 21:46:38.880999

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20286263e186"
down_revision: Union[str, None] = "aadd9ba89966"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("user", "users")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("users", "user")
    # ### end Alembic commands ###
