"""Add hero model

Revision ID: 7635b2582350
Revises:
Create Date: 2025-01-05 21:06:00.805078

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "7635b2582350"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
