"""Hero model: add user foreign key

Revision ID: 94549f3a62d0
Revises: d50189d305f3
Create Date: 2025-01-24 23:14:06.037196

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94549f3a62d0"
down_revision: Union[str, None] = "d50189d305f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hero", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "hero", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "hero", type_="foreignkey")
    op.drop_column("hero", "user_id")
    # ### end Alembic commands ###
