"""Add user role field

Revision ID: 9f61a0c824dd
Revises: a9bb57b46b15
Create Date: 2025-02-04 02:45:02.700952

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f61a0c824dd"
down_revision: Union[str, None] = "a9bb57b46b15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "role", sa.Enum("admin", "staff", "active", name="userrole"), nullable=True
        ),
    )
    op.create_index(op.f("ix_user_role"), "user", ["role"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_role"), table_name="user")
    op.drop_column("user", "role")
    # ### end Alembic commands ###
