"""base table with timestamped model

Revision ID: c5da92aa72eb
Revises: 20055947a674
Create Date: 2025-07-11 18:52:33.541748

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5da92aa72eb"
down_revision: Union[str, None] = "20055947a674"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permission",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column("permission", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column(
        "permission_group",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "permission_group", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("permission_group", "updated_at")
    op.drop_column("permission_group", "created_at")
    op.drop_column("permission", "updated_at")
    op.drop_column("permission", "created_at")
    # ### end Alembic commands ###
