"""Added hero table

Revision ID: cfd29d6602dc
Revises:
Create Date: 2025-01-03 21:21:08.236870

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "cfd29d6602dc"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
