"""Add created_at field

Revision ID: d1f2dd0406ae
Revises: 94549f3a62d0
Create Date: 2025-01-28 02:59:04.085170

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1f2dd0406ae"
down_revision: Union[str, None] = "94549f3a62d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hero", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("created_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "created_at")
    op.drop_column("hero", "created_at")
    # ### end Alembic commands ###
