"""initial migration

Revision ID: 464fdae252ea
Revises:
Create Date: 2025-01-03 18:51:20.014246

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "464fdae252ea"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
