name: Pre-commit

on:
  pull_request:
    branches: [ "*" ]

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1

      - name: Run pre-commit
        run: |
          echo $PWD
          ls -alh
          pre-commit run --all-files
