name: Tests
run-name: Run tests

on:
  push:
    branches: ["master"]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: ["*"]

jobs:
  tests:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.13"]
        docker-version: ["27.2"]
        docker-channel: ["stable"]

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-docker-action@v4
        with:
          docker_version: ${{ matrix.docker-version }}
          docker_channel: ${{ matrix.docker-channel }}

      - name: Prepare test environment
        run: |
          export UV_LINK_MODE=copy
          export PYTHON_VERSION=${{ matrix.python-version }}
          docker compose -f docker-compose.test.ci.yaml up -d

      - name: Run Tests
        run: |
          # Synchronize with the test command: core/services/runners/test.py
          docker exec -t api_test pytest --cov=. --cov-report=xml --cov-fail-under=80 --cov-branch --no-cov-on-fail --cov-config=.coveragerc --cache-clear --disable-warnings

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
